"use client";
import React, { useState } from "react";
import { Roboto } from "@next/font/google";
import styles from "./NewPlFirstPage.module.css";
import "./KfsDocs.css";
import OTPBottomSheet from "./NewPlOtpBottomSheet/PlOTPBottomSheet";
import Mandate from "./Mandate.js";
const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const KfsDocs = () => {
  const [isOtpBottomSheetVisible, setIsOtpBottomSheetVisible] = useState(false);
  const [upotp, setUpOtp] = useState("");
  const [otpStatus, setOtpStatus] = useState("");
  const [activeContainer, setActiveContainer] = useState("KfsDocs");

  const handleNextClick = () => {
    setUpOtp("");
    setIsOtpBottomSheetVisible(true);
  };

  const handleVerifyOTP = () => {
    setOtpStatus("Verified");
    setIsOtpBottomSheetVisible(false);
    setActiveContainer("Mandate");
  };

  return (
    <>
      {activeContainer === "Mandate" ? (
        <Mandate />
      ) : (
        <div className={`${roboto.className} kfspage-container`}>
          <div className="newfirstcard-container-kddc">
            <form className={styles.form}>
              <div className={styles.formGroup}>
                <h1 className="fixed-header">Document generated by YUBI KFS</h1>
              </div>

              {/* Full iframe content */}
              <div
                className="iframedoc"
                style={{
                  backgroundColor: "#f7f6fd",
                  width: "100%",
                  height: "calc(100vh - 120px)", // Adjust for header and button height
                  overflow: "hidden",
                }}
              >
                <iframe
                  src="https://www.credithaat.com"
                  title="Document Viewer"
                  style={{
                    width: "100%",
                    height: "100%", // Let iframe fill the container
                    border: "none",
                  }}
                />
              </div>
              {console.log("calling next button")}
              {/* Sticky Button at Bottom */}
              <div className={styles.stickyButton}>
                <button
                  type="button"
                  className={`${styles.button} ${styles.submitButton}`}
                  onClick={() => {
                    console.log("Clicked Next");
                    setIsOtpBottomSheetVisible(true);
                  }}
                >
                  Next
                </button>

                {console.log("after next button")}
              </div>
            </form>
          </div>

          {/* OTP Bottom Sheet Modal */}
          {isOtpBottomSheetVisible && (
            <OTPBottomSheet
              isVisible={isOtpBottomSheetVisible}
              verifyOTP={handleVerifyOTP}
              upotp={upotp}
              otpStatus={otpStatus}
              setUpOtp={setUpOtp}
            />
          )}
        </div>
      )}
    </>
  );
};

export default KfsDocs;

// "use client";
// import React, { useState } from "react";
// import { Roboto } from "@next/font/google";
// import styles from "./NewPlFirstPage.module.css";
// import "./KfsDocs.css";
// import OTPBottomSheet from "../NewPlOtpBottomSheet/PlOTPBottomSheet";

// const roboto = Roboto({
//   weight: ["400", "700"],
//   subsets: ["latin"],
// });

// const KfsDocs = () => {
//   const [isOtpBottomSheetVisible, setIsOtpBottomSheetVisible] = useState(false);
//   const [upotp, setUpOtp] = useState("");
//   const [otpStatus, setOtpStatus] = useState("");
//   const handleNextClick = () => {
//     setUpOtp("");
//     // Show OTP Bottom Sheet
//     setIsOtpBottomSheetVisible(true);
//   };

//   const handleVerifyOTP = () => {
//     setOtpStatus("Verified");
//     setIsOtpBottomSheetVisible(false);
//   };

//   return (
//     <div className={`${roboto.className} page-container`}>
//         <div className="newfirstcard-container-ddc" style={{ boxSizing: "content-box" }}>
//           <form className={styles.form}>
//           <div className={styles.formGroup}>
//               <h1 className="fixed-header">Document generated by YUBI KFS</h1>
//           </div>

//       {/* Scrollable Content */}
//       <div className="iframedoc"
//        style={{backgroundColor:"#f7f6fd" }}>
//         <iframe
//           src="https://example.com/document.pdf"
//           title="Document Viewer"

//         />
//       </div>

//       {/* Sticky Button at Bottom */}
//       <div className={styles.stickyButton}>
//         <button
//           type="button"
//           className={`${styles.button} ${styles.submitButton}`}
//           onClick={handleNextClick}
//         >
//           Next
//         </button>

//       </div>
//       </form>
//       </div>

//       {/* OTP Bottom Sheet Modal */}
//       {isOtpBottomSheetVisible && (
//         <OTPBottomSheet
//           isVisible={isOtpBottomSheetVisible}
//           verifyOTP={handleVerifyOTP}
//           upotp={upotp}
//           otpStatus={otpStatus}
//           setUpOtp={setUpOtp}
//         />
//       )}
//     </div>
//   );
// };

// export default KfsDocs;
